/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import shellscene from "./shellscene";
import winluckydraw from "./winluckydraw";
import itemreward from "./itemreward";
import winsetting from "./winsetting";
import btn_back from "./btn_back";
import com_switch from "./com_switch";
import winmoregame from "./winmoregame";
import winpromotionreward from "./winpromotionreward";
import btn_confirm from "./btn_confirm";
import com_level_stars from "./com_level_stars";
import guidefinger from "./guidefinger";
import com_wrongnum from "./com_wrongnum";
import com_loader from "./com_loader";
import wincollectiongame from "./wincollectiongame";
import btn_col_next from "./btn_col_next";
import btn_col_last from "./btn_col_last";
import btn_lucky from "./btn_lucky";
import wintreasurebox from "./wintreasurebox";
import com_addfloat from "./com_addfloat";
import com_service from "./com_service";
import btn_moregame from "./btn_moregame";
import btn_luckdraw from "./btn_luckdraw";
import winenergyover from "./winenergyover";
import com_energy_reward from "./com_energy_reward";
import btn_energy_close from "./btn_energy_close";
import com_box_close from "./com_box_close";
import com_imgright from "./com_imgright";
import com_imgwrong from "./com_imgwrong";
import wingamefail from "./wingamefail";
import btn_restart from "./btn_restart";
import btn_delay from "./btn_delay";
import goservice from "./goservice";
import collectgame_anipanel from "./collectgame_anipanel";
import getreward_btnget from "./getreward_btnget";
import promotion_close from "./promotion_close";
import winmustshare from "./winmustshare";
import mustshare_btnok from "./mustshare_btnok";
import gamesheel_bgm from "./gamesheel_bgm";
import winofflinebox from "./winofflinebox";
import com_gameicon_item from "./com_gameicon_item";
import com_gameicon from "./com_gameicon";
import getreward_btn from "./getreward_btn";
import btn_nextmore_reward from "./btn_nextmore_reward";
import guidemask from "./guidemask";
import guidemaskcircle from "./guidemaskcircle";
import gamerecommenditem from "./gamerecommenditem";
import guidemaskclick from "./guidemaskclick";
import btn_gameshare from "./btn_gameshare";
import rankbtn2 from "./rankbtn2";
import closebtn from "./closebtn";
import rankbtn1 from "./rankbtn1";
import rankrender from "./rankrender";
import headicon from "./headicon";
import winrecommend from "./winrecommend";
import recommenditem from "./recommenditem";
import com_back_game from "./com_back_game";
import itemmoregame from "./itemmoregame";
import btn_more from "./btn_more";
import winaddfloat from "./winaddfloat";
import Button_IKnow from "./Button_IKnow";
import wincsrewards from "./wincsrewards";
import btn_open from "./btn_open";
import btn_recommend_close from "./btn_recommend_close";
import wingetreward from "./wingetreward";
import btn_receive_reward from "./btn_receive_reward";
import itemrenderpanel from "./itemrenderpanel";
import item_com from "./item_com";
import animation_gameover from "./animation_gameover";
import gamescene from "./gamescene";
import gamewinscene from "./gamewinscene";
import com_img1 from "./com_img1";
import btn_tip from "./btn_tip";
import com_progress from "./com_progress";
import com_level from "./com_level";
import btn_back_home from "./btn_back_home";
import btn_next from "./btn_next";
import gameover_progress from "./gameover_progress";
import winlevel from "./winlevel";
import btn_close from "./btn_close";
import item_level from "./item_level";
import com_addmy from "./com_addmy";
import btn_receive from "./btn_receive";
import lobbyscene from "./lobbyscene";
import com_energy from "./com_energy";
import btn_img from "./btn_img";
import winfreeenergy from "./winfreeenergy";
import winrank from "./winrank";
import com_gold from "./com_gold";
import btn_start from "./btn_start";
import btn_rank from "./btn_rank";
import btn_setting from "./btn_setting";
import btn_gift from "./btn_gift";
import com_imgdebug from "./com_imgdebug";
import winauthor from "./winauthor";
import gamebtn_back from "./gamebtn_back";
import btn_yellowgetreward from "./btn_yellowgetreward";
import wingetreward_energy from "./wingetreward_energy";

export default class gameBinder{
	public static bindAll():void {
		fairygui.UIObjectFactory.setPackageItemExtension(shellscene.URL, shellscene);
		fairygui.UIObjectFactory.setPackageItemExtension(winluckydraw.URL, winluckydraw);
		fairygui.UIObjectFactory.setPackageItemExtension(itemreward.URL, itemreward);
		fairygui.UIObjectFactory.setPackageItemExtension(winsetting.URL, winsetting);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_back.URL, btn_back);
		fairygui.UIObjectFactory.setPackageItemExtension(com_switch.URL, com_switch);
		fairygui.UIObjectFactory.setPackageItemExtension(winmoregame.URL, winmoregame);
		fairygui.UIObjectFactory.setPackageItemExtension(winpromotionreward.URL, winpromotionreward);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_confirm.URL, btn_confirm);
		fairygui.UIObjectFactory.setPackageItemExtension(com_level_stars.URL, com_level_stars);
		fairygui.UIObjectFactory.setPackageItemExtension(guidefinger.URL, guidefinger);
		fairygui.UIObjectFactory.setPackageItemExtension(com_wrongnum.URL, com_wrongnum);
		fairygui.UIObjectFactory.setPackageItemExtension(com_loader.URL, com_loader);
		fairygui.UIObjectFactory.setPackageItemExtension(wincollectiongame.URL, wincollectiongame);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_col_next.URL, btn_col_next);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_col_last.URL, btn_col_last);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_lucky.URL, btn_lucky);
		fairygui.UIObjectFactory.setPackageItemExtension(wintreasurebox.URL, wintreasurebox);
		fairygui.UIObjectFactory.setPackageItemExtension(com_addfloat.URL, com_addfloat);
		fairygui.UIObjectFactory.setPackageItemExtension(com_service.URL, com_service);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_moregame.URL, btn_moregame);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_luckdraw.URL, btn_luckdraw);
		fairygui.UIObjectFactory.setPackageItemExtension(winenergyover.URL, winenergyover);
		fairygui.UIObjectFactory.setPackageItemExtension(com_energy_reward.URL, com_energy_reward);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_energy_close.URL, btn_energy_close);
		fairygui.UIObjectFactory.setPackageItemExtension(com_box_close.URL, com_box_close);
		fairygui.UIObjectFactory.setPackageItemExtension(com_imgright.URL, com_imgright);
		fairygui.UIObjectFactory.setPackageItemExtension(com_imgwrong.URL, com_imgwrong);
		fairygui.UIObjectFactory.setPackageItemExtension(wingamefail.URL, wingamefail);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_restart.URL, btn_restart);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_delay.URL, btn_delay);
		fairygui.UIObjectFactory.setPackageItemExtension(goservice.URL, goservice);
		fairygui.UIObjectFactory.setPackageItemExtension(collectgame_anipanel.URL, collectgame_anipanel);
		fairygui.UIObjectFactory.setPackageItemExtension(getreward_btnget.URL, getreward_btnget);
		fairygui.UIObjectFactory.setPackageItemExtension(promotion_close.URL, promotion_close);
		fairygui.UIObjectFactory.setPackageItemExtension(winmustshare.URL, winmustshare);
		fairygui.UIObjectFactory.setPackageItemExtension(mustshare_btnok.URL, mustshare_btnok);
		fairygui.UIObjectFactory.setPackageItemExtension(gamesheel_bgm.URL, gamesheel_bgm);
		fairygui.UIObjectFactory.setPackageItemExtension(winofflinebox.URL, winofflinebox);
		fairygui.UIObjectFactory.setPackageItemExtension(com_gameicon_item.URL, com_gameicon_item);
		fairygui.UIObjectFactory.setPackageItemExtension(com_gameicon.URL, com_gameicon);
		fairygui.UIObjectFactory.setPackageItemExtension(getreward_btn.URL, getreward_btn);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_nextmore_reward.URL, btn_nextmore_reward);
		fairygui.UIObjectFactory.setPackageItemExtension(guidemask.URL, guidemask);
		fairygui.UIObjectFactory.setPackageItemExtension(guidemaskcircle.URL, guidemaskcircle);
		fairygui.UIObjectFactory.setPackageItemExtension(gamerecommenditem.URL, gamerecommenditem);
		fairygui.UIObjectFactory.setPackageItemExtension(guidemaskclick.URL, guidemaskclick);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_gameshare.URL, btn_gameshare);
		fairygui.UIObjectFactory.setPackageItemExtension(rankbtn2.URL, rankbtn2);
		fairygui.UIObjectFactory.setPackageItemExtension(closebtn.URL, closebtn);
		fairygui.UIObjectFactory.setPackageItemExtension(rankbtn1.URL, rankbtn1);
		fairygui.UIObjectFactory.setPackageItemExtension(rankrender.URL, rankrender);
		fairygui.UIObjectFactory.setPackageItemExtension(headicon.URL, headicon);
		fairygui.UIObjectFactory.setPackageItemExtension(winrecommend.URL, winrecommend);
		fairygui.UIObjectFactory.setPackageItemExtension(recommenditem.URL, recommenditem);
		fairygui.UIObjectFactory.setPackageItemExtension(com_back_game.URL, com_back_game);
		fairygui.UIObjectFactory.setPackageItemExtension(itemmoregame.URL, itemmoregame);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_more.URL, btn_more);
		fairygui.UIObjectFactory.setPackageItemExtension(winaddfloat.URL, winaddfloat);
		fairygui.UIObjectFactory.setPackageItemExtension(Button_IKnow.URL, Button_IKnow);
		fairygui.UIObjectFactory.setPackageItemExtension(wincsrewards.URL, wincsrewards);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_open.URL, btn_open);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_recommend_close.URL, btn_recommend_close);
		fairygui.UIObjectFactory.setPackageItemExtension(wingetreward.URL, wingetreward);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_receive_reward.URL, btn_receive_reward);
		fairygui.UIObjectFactory.setPackageItemExtension(itemrenderpanel.URL, itemrenderpanel);
		fairygui.UIObjectFactory.setPackageItemExtension(item_com.URL, item_com);
		fairygui.UIObjectFactory.setPackageItemExtension(animation_gameover.URL, animation_gameover);
		fairygui.UIObjectFactory.setPackageItemExtension(gamescene.URL, gamescene);
		fairygui.UIObjectFactory.setPackageItemExtension(gamewinscene.URL, gamewinscene);
		fairygui.UIObjectFactory.setPackageItemExtension(com_img1.URL, com_img1);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_tip.URL, btn_tip);
		fairygui.UIObjectFactory.setPackageItemExtension(com_progress.URL, com_progress);
		fairygui.UIObjectFactory.setPackageItemExtension(com_level.URL, com_level);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_back_home.URL, btn_back_home);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_next.URL, btn_next);
		fairygui.UIObjectFactory.setPackageItemExtension(gameover_progress.URL, gameover_progress);
		fairygui.UIObjectFactory.setPackageItemExtension(winlevel.URL, winlevel);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_close.URL, btn_close);
		fairygui.UIObjectFactory.setPackageItemExtension(item_level.URL, item_level);
		fairygui.UIObjectFactory.setPackageItemExtension(com_addmy.URL, com_addmy);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_receive.URL, btn_receive);
		fairygui.UIObjectFactory.setPackageItemExtension(lobbyscene.URL, lobbyscene);
		fairygui.UIObjectFactory.setPackageItemExtension(com_energy.URL, com_energy);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_img.URL, btn_img);
		fairygui.UIObjectFactory.setPackageItemExtension(winfreeenergy.URL, winfreeenergy);
		fairygui.UIObjectFactory.setPackageItemExtension(winrank.URL, winrank);
		fairygui.UIObjectFactory.setPackageItemExtension(com_gold.URL, com_gold);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_start.URL, btn_start);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_rank.URL, btn_rank);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_setting.URL, btn_setting);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_gift.URL, btn_gift);
		fairygui.UIObjectFactory.setPackageItemExtension(com_imgdebug.URL, com_imgdebug);
		fairygui.UIObjectFactory.setPackageItemExtension(winauthor.URL, winauthor);
		fairygui.UIObjectFactory.setPackageItemExtension(gamebtn_back.URL, gamebtn_back);
		fairygui.UIObjectFactory.setPackageItemExtension(btn_yellowgetreward.URL, btn_yellowgetreward);
		fairygui.UIObjectFactory.setPackageItemExtension(wingetreward_energy.URL, wingetreward_energy);
	}
}